// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3_kUdpvlu_XvZWfv3S0pOOk7igywpi8E',
    appId: '1:583916606624:web:40d5d898413467ac2ca5c5',
    messagingSenderId: '583916606624',
    projectId: 'work-connect-5d5a8',
    authDomain: 'work-connect-5d5a8.firebaseapp.com',
    storageBucket: 'work-connect-5d5a8.firebasestorage.app',
    measurementId: 'G-GH0D5BJ6K2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDacFKvpZKaW0egKo-PnOJ9YSimdocfU5U',
    appId: '1:583916606624:android:774145798f69980d2ca5c5',
    messagingSenderId: '583916606624',
    projectId: 'work-connect-5d5a8',
    storageBucket: 'work-connect-5d5a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0cH07vtFJJ84z8dkybHe607xVQAIHn7k',
    appId: '1:583916606624:ios:b21da4897823f8972ca5c5',
    messagingSenderId: '583916606624',
    projectId: 'work-connect-5d5a8',
    storageBucket: 'work-connect-5d5a8.firebasestorage.app',
    iosBundleId: 'com.example.workConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0cH07vtFJJ84z8dkybHe607xVQAIHn7k',
    appId: '1:583916606624:ios:b21da4897823f8972ca5c5',
    messagingSenderId: '583916606624',
    projectId: 'work-connect-5d5a8',
    storageBucket: 'work-connect-5d5a8.firebasestorage.app',
    iosBundleId: 'com.example.workConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3_kUdpvlu_XvZWfv3S0pOOk7igywpi8E',
    appId: '1:583916606624:web:ee866bdf3f5896412ca5c5',
    messagingSenderId: '583916606624',
    projectId: 'work-connect-5d5a8',
    authDomain: 'work-connect-5d5a8.firebaseapp.com',
    storageBucket: 'work-connect-5d5a8.firebasestorage.app',
    measurementId: 'G-JFHSC6LC8N',
  );

}